$env:ASPNETCORE_ENVIRONMENT='Development'
$env:ASPNETCORE_URLS='http://0.0.0.0:5000'
$env:ConnectionStrings__DefaultConnection='Host=localhost;Database=delivery_db;Username=postgres;Password=Admin@Ts2x04_;Maximum Pool Size=1024;'
$env:ConnectionStrings__Redis='localhost:6379'
$env:AI_SERVICE_URL='http://localhost:8000'
$env:AI_SERVICE_API_KEY='test-api-key'
$env:Routing__LocalOsrmUrl='http://localhost:5001'
$env:MessageBroker__Host='localhost'
$env:Jwt__Key='DeliverySmartRoutingSystem_SuperSecretKey_2024'
$env:Jwt__Issuer='DeliveryBackendApi'
$env:Jwt__Audience='DeliveryClients'
$env:Authentication__RequireSecureCookie='false'
$env:MessageBroker__Port='5672'
$env:MessageBroker__Username='guest'
$env:MessageBroker__Password='guest'
dotnet run
